--Drops all tables in Crickets Database
DROP TABLE CricketTestInstance CASCADE CONSTRAINTS;
DROP TABLE TestInstance CASCADE CONSTRAINTS;
DROP TABLE Test CASCADE CONSTRAINTS;
DROP TABLE Project CASCADE CONSTRAINTS;
DROP TABLE Observer CASCADE CONSTRAINTS;
DROP TABLE Cricket CASCADE CONSTRAINTS;